FROM gradle:8.7-jdk17

WORKDIR /app

# Copiar todo o projeto
COPY . /app

# Expor porta da aplicação e porta do LiveReload
EXPOSE 8080 35729

# Dar permissão de execução ao script de start
RUN chmod +x start.sh

# Baixar dependências do projeto
RUN gradle getDependencies --no-daemon

# Script que monitora mudanças e executa bootRun
CMD ["sh", "start.sh"]
